-- A realistic NSE universe for the simulator. Names only; prices come from
-- the provider. Idempotent.
INSERT INTO symbols (symbol, name, exchange) VALUES
  ('RELIANCE',   'Reliance Industries',            'NSE'),
  ('TCS',        'Tata Consultancy Services',      'NSE'),
  ('HDFCBANK',   'HDFC Bank',                      'NSE'),
  ('INFY',       'Infosys',                        'NSE'),
  ('ICICIBANK',  'ICICI Bank',                     'NSE'),
  ('HINDUNILVR', 'Hindustan Unilever',             'NSE'),
  ('SBIN',       'State Bank of India',            'NSE'),
  ('BHARTIARTL', 'Bharti Airtel',                  'NSE'),
  ('ITC',        'ITC',                            'NSE'),
  ('KOTAKBANK',  'Kotak Mahindra Bank',            'NSE'),
  ('LT',         'Larsen & Toubro',                'NSE'),
  ('AXISBANK',   'Axis Bank',                      'NSE'),
  ('ASIANPAINT', 'Asian Paints',                   'NSE'),
  ('MARUTI',     'Maruti Suzuki',                  'NSE'),
  ('BAJFINANCE', 'Bajaj Finance',                  'NSE'),
  ('HCLTECH',    'HCL Technologies',               'NSE'),
  ('WIPRO',      'Wipro',                          'NSE'),
  ('SUNPHARMA',  'Sun Pharmaceutical',             'NSE'),
  ('TITAN',      'Titan Company',                  'NSE'),
  ('ULTRACEMCO', 'UltraTech Cement',               'NSE'),
  ('NESTLEIND',  'Nestle India',                   'NSE'),
  ('ONGC',       'Oil & Natural Gas Corp',         'NSE'),
  ('NTPC',       'NTPC',                           'NSE'),
  ('POWERGRID',  'Power Grid Corp',                'NSE'),
  ('TATAMOTORS', 'Tata Motors',                    'NSE'),
  ('TATASTEEL',  'Tata Steel',                     'NSE'),
  ('JSWSTEEL',   'JSW Steel',                      'NSE'),
  ('M&M',        'Mahindra & Mahindra',            'NSE'),
  ('ADANIENT',   'Adani Enterprises',              'NSE'),
  ('ADANIPORTS', 'Adani Ports',                    'NSE'),
  ('COALINDIA',  'Coal India',                     'NSE'),
  ('BAJAJFINSV', 'Bajaj Finserv',                  'NSE'),
  ('TECHM',      'Tech Mahindra',                  'NSE'),
  ('HDFCLIFE',   'HDFC Life Insurance',            'NSE'),
  ('SBILIFE',    'SBI Life Insurance',             'NSE'),
  ('DRREDDY',    'Dr. Reddys Laboratories',        'NSE'),
  ('CIPLA',      'Cipla',                          'NSE'),
  ('DIVISLAB',   'Divis Laboratories',             'NSE'),
  ('EICHERMOT',  'Eicher Motors',                  'NSE'),
  ('HEROMOTOCO', 'Hero MotoCorp',                  'NSE'),
  ('BRITANNIA',  'Britannia Industries',           'NSE'),
  ('GRASIM',     'Grasim Industries',              'NSE'),
  ('INDUSINDBK', 'IndusInd Bank',                  'NSE'),
  ('BPCL',       'Bharat Petroleum',               'NSE'),
  ('HINDALCO',   'Hindalco Industries',            'NSE'),
  ('APOLLOHOSP', 'Apollo Hospitals',               'NSE'),
  ('TATACONSUM', 'Tata Consumer Products',         'NSE'),
  ('SHRIRAMFIN', 'Shriram Finance',                'NSE'),
  ('BEL',        'Bharat Electronics',             'NSE'),
  ('TRENT',      'Trent',                          'NSE'),
  ('ZOMATO',     'Zomato',                         'NSE'),
  ('PAYTM',      'One97 Communications (Paytm)',   'NSE'),
  ('NYKAA',      'FSN E-Commerce (Nykaa)',         'NSE'),
  ('POLICYBZR',  'PB Fintech (Policybazaar)',      'NSE'),
  ('IRCTC',      'IRCTC',                          'NSE'),
  ('IDEA',       'Vodafone Idea',                  'NSE'),
  ('YESBANK',    'Yes Bank',                       'NSE'),
  ('SUZLON',     'Suzlon Energy',                  'NSE'),
  ('RVNL',       'Rail Vikas Nigam',               'NSE'),
  ('IRFC',       'Indian Railway Finance Corp',    'NSE')
ON CONFLICT (symbol) DO NOTHING;
